### ISSUE TITLE
[JENKINS-35414] Folders don't show up in dashboard view after upgrade

### ISSUE THREAD

**Issue by TobiX** [jenkinsci/dashboard-view-plugin#212]
<p>After upgrading Jenkins from 1.658 to 2.7 and Dashboard View Plugin from 2.9.7 to 2.9.10, the folders do not appear in a job list created in the Dashboard View.<br/>
Steps to reproduce :</p>
<ul class="alternate" type="square">
	<li>Jenkins with Folder and Dashboard plugins</li>
	<li>Create a folder</li>
	<li>Create a dashboard view and use regular expression ".*" to include all jobs.</li>
</ul>

<p>Playing with other filters, or manually selecting the folders to display doesn't work either.</p>

---
<details><summary><i>Originally reported by <a title="Emmanuel Guérin" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=eguerints">eguerints</a>, imported from: <a href="https://issues.jenkins.io/browse/JENKINS-35414" target="_blank">Folders don't show up in dashboard view after upgrade</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Tobias Gruetzmacher" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=tgr">tgr</a>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022-10-30
</ul></i>
</details>

**Comment by eoc-ross** [comment]
It appears that on line 48

https://github.com/jenkinsci/dashboard-view-plugin/blob/8ce39335d550ead0fa3e83a237de616d3fbc4369/src/main/resources/hudson/plugins/view/dashboard/Dashboard/main.jelly#L47-L49

The job list (referenced by `jobs`) is used. Unfortunately `jobs`, is filled in with instances of Job class only, whether Folder, MultiBranchPipeline and Organization Folder are not.

However, the list is only shown when selecting
![image](https://user-images.githubusercontent.com/51781826/210073219-3cd04f03-fc66-439d-9fdb-04ce2d0b5990.png)
So, it should be safe to assume that the "standadrd jenkins ListView" behaviour to show `items` instead of `jobs` would be fine.

I'm willing to make a PR for the fix if it's ok. Also I'd like to include some other changes:
- scheduling a new build in the other portlet has the same problem: doesn't work for item in subfolder
- make "job filters" work with subfolder (i.e.: using regex `.*/master` which shows only the top element in "standard jenkins view" and recursively only master branches in "Unstable jobs" portlet)

**Comment by kerrhome** [comment]
List view works for also displaying Multi-Branch Pipelines, so I'll use that, but what we wanted was to use Dashboard to take advantage of the portlets.  It's too bad that this is still an open issue because Dashboard View is awesome.
