### ISSUE TITLE
iframe portlet sandbox

### ISSUE THREAD

**Issue by GeneMyslinsky** [jenkinsci/dashboard-view-plugin#304]
### Describe your use-case which is not covered by existing documentation.

I want to disable the sandboxing or at least allow same-origin javascript in the iframe portlet. I noticed the code had variables [DO_NOT_USE_SANDBOX and SANDBOX_VALUE](https://github.com/jenkinsci/dashboard-view-plugin/blob/main/src/main/java/hudson/plugins/view/dashboard/core/IframePortlet.java) which are later referenced in the jelly file

I tried to set them on the jenkins script console but it still did not remove or modify the sandbox

System.setProperty("hudson.plugins.view.dashboard.core.IframePortlet.doNotUseSandbox", "true"))
System.setProperty("hudson.plugins.view.dashboard.core.IframePortlet.sandboxAttributeValue","allow-scripts"))

how could I use this functionality to allow javascript to run from the same host?

**Comment by TobiX** [comment]
Hmm, that's strange. Those properties were introduced when fixing [SECURITY-2559](https://www.jenkins.io/security/advisory/2022-03-15/#SECURITY-2559), but I admit I never tested if they work as intended...

Let my verify this...

**Comment by TobiX** [comment]
Okay, the properties work as intended, BUT since they are stored in static variables, they need to be set early enough (before the first `IframePortlet` is loaded) to take effect.

I couldn't apply the property from the Script Console at all, so you probably have to apply it from the command line (see https://www.jenkins.io/doc/book/managing/system-properties/#usage)
